In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Churn_model.csv')

In [3]:
df.drop(['Unnamed: 0'],axis = 1,inplace = True)
df.head()


SeniorCitizen  Partner  Dependents  MultipleLines  InternetService  \
0              0        0           0              0                1   
1              0        1           0              2                1   
2              0        1           0              1                0   
3              1        1           0              0                1   
4              0        0           0              1                0   

   OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0               2             0                 0            0            0   
1               0             0                 0            0            0   
2               0             2                 0            0            0   
3               2             0                 0            0            0   
4               0             0                 0            0            0   

   StreamingMovies  Contract  PaperlessBilling  PaymentMethod  Churn  \
0                0       0.0                 1              1      1   
1                2       0.0                 1              2      1   
2                2       0.0                 1              0      1   
3                0       0.0                 1              0      1   
4                0       0.0                 1              3      1   

     tenure  MonthlyCharges  TotalCharges  
0  0.758426       -0.278080      0.286083  
1  1.613592       -0.873018      0.213067  
2 -0.911184        0.692433     -0.646863  
3 -0.829739       -1.486236     -0.888808  
4  0.391927        0.057611      0.212957

In [4]:
X = df.drop(['Churn'],axis = 1)
y = df.loc[:,'Churn']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 8)

In [7]:
from sklearn import svm

In [8]:
svc = svm.SVC(class_weight='balanced', kernel='linear')

In [9]:
model_svc = svc.fit(X_train,y_train)

In [10]:
y_pred = model_svc.predict(X_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,roc_auc_score

In [12]:
print(confusion_matrix(y_test,y_pred))

[[562 448]
 [129 930]]


In [13]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.56      0.66      1010
           1       0.67      0.88      0.76      1059

    accuracy                           0.72      2069
   macro avg       0.74      0.72      0.71      2069
weighted avg       0.74      0.72      0.71      2069



In [14]:
accuracy_score(y_test,y_pred)

0.7211213146447559

In [15]:
roc_auc_score(y_test,y_pred)

0.7173113062014417

_________________________________________________________________________________________

____________________________________________________________________________________

In [16]:
svc2 =svm.SVC(class_weight='balanced', probability=True)

In [17]:
model_svc2 = svc2.fit(X_train,y_train)

In [18]:
y_pred2 = model_svc2.predict(X_test)

In [19]:
print(confusion_matrix(y_test,y_pred2))

[[726 284]
 [205 854]]


In [20]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.78      0.72      0.75      1010
           1       0.75      0.81      0.78      1059

    accuracy                           0.76      2069
   macro avg       0.77      0.76      0.76      2069
weighted avg       0.76      0.76      0.76      2069



In [21]:
accuracy_score(y_test,y_pred2)

0.763653939101015

________________________________________________________________________________

In [22]:
svc3 =svm.SVC(class_weight='balanced', probability=True,kernel='linear')

In [23]:
model_svc3 = svc3.fit(X_train,y_train)

In [24]:
y_pred3 = model_svc3.predict(X_test)

In [25]:
confusion_matrix(y_test,y_pred3)

array([[562, 448],
       [129, 930]], dtype=int64)

In [26]:
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.81      0.56      0.66      1010
           1       0.67      0.88      0.76      1059

    accuracy                           0.72      2069
   macro avg       0.74      0.72      0.71      2069
weighted avg       0.74      0.72      0.71      2069



In [27]:
accuracy_score(y_test,y_pred3)

0.7211213146447559

________________________________________________________________________________

In [28]:
svc4 =svm.SVC(class_weight='balanced', probability=True,kernel='poly')

In [29]:
model_svc4 = svc4.fit(X_train,y_train)

In [30]:
y_pred4 = model_svc4.predict(X_test)

In [31]:
print(confusion_matrix(y_test,y_pred4))

[[714 296]
 [212 847]]


In [32]:
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.77      0.71      0.74      1010
           1       0.74      0.80      0.77      1059

    accuracy                           0.75      2069
   macro avg       0.76      0.75      0.75      2069
weighted avg       0.76      0.75      0.75      2069



In [33]:
accuracy_score(y_test,y_pred4)

0.7544707588206864